version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: walkman444/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    restart: always

  frontend:
    image: walkman444/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    image: walkman444/foodgram_gateway
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 8001:80
    depends_on:
      - backend
      - frontend
    restart: always